// packages/@react/src/components/avatar/index.tsx
import React from 'react'

const UAvatar: React.FC = () => {
  return (
    <>
      <div className="h-6 w-6 mb-4 lg:mb-0 mr-4">
        <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_3_0.png" alt='img' className="h-full w-full rounded-full overflow-hidden shadow" />
      </div>

      <div className="h-8 w-8 mb-4 lg:mb-0 mr-4">
        <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_3_1.png" alt='img' className="h-full w-full rounded-full overflow-hidden shadow" />
      </div>

      <div className="h-10 w-10 mb-4 lg:mb-0 mr-4">
        <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_3_2.png" alt='img' className="h-full w-full rounded-full overflow-hidden shadow" />
      </div>

      <div className="h-12 w-12 mb-4 lg:mb-0 mr-4">
        <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_3_3.png" alt='img' className="h-full w-full rounded-full overflow-hidden shadow" />
      </div>

      <div className="h-16 w-16 mb-4 lg:mb-0 mr-4">
        <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_3_4.png" alt='img' className="h-full w-full rounded-full overflow-hidden shadow" />
      </div>

      <div className="h-20 w-20 mb-4 lg:mb-0 mr-4">
        <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_3_5.png" alt='img' className="h-full w-full rounded-full overflow-hidden shadow" />
      </div>

      <div className="h-24 w-24 mb-4 lg:mb-0 mr-4">
        <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_3_6.png" alt='img' className="h-full w-full rounded-full overflow-hidden shadow" />
      </div>

      <div className="h-32 w-32 mb-4 lg:mb-0 mr-4">
        <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_3_7.png" alt='img' className="h-full w-full rounded-full overflow-hidden shadow" />
      </div>

      <div className="w-12 h-12 bg-cover bg-center rounded-md">
        <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_4_0.png" alt='img' className="h-full w-full overflow-hidden object-cover rounded-full border-2 border-white dark:border-gray-700 shadow" />
      </div>

      <div className="w-12 h-12 bg-cover rounded-md -ml-2">
        <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_4_1.png" alt='img' className="h-full w-full overflow-hidden object-cover rounded-full border-2 border-white dark:border-gray-700 shadow" />
      </div>

      <div className="w-12 h-12 bg-cover rounded-md bg-center -ml-2">
        <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_4_2.png" alt='img' className="h-full w-full overflow-hidden object-cover rounded-full border-2 border-white dark:border-gray-700 shadow" />
      </div>

      <div className="w-12 h-12 bg-cover rounded-md -ml-2">
        <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_4_3.png" alt='img' className="h-full w-full overflow-hidden object-cover object-center rounded-full border-2 border-white dark:border-gray-700 shadow" />
      </div>

      <div className="w-12 h-12 bg-cover rounded-md -ml-2">
        <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_4_4.png" alt='img' className="h-full w-full overflow-hidden object-cover object-center rounded-full border-2 border-white dark:border-gray-700 shadow" />
      </div>
    </>
  )
}

export default UAvatar

// packages/@vue/src/components/avatar/avatar.vue
<script setup lang="ts">
defineOptions({
  name: 'UAvatar',
})
</script>

<template>
  <div class="h-6 w-6 mb-4 lg:mb-0 mr-4">
    <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_3_0.png" alt="" class="h-full w-full rounded-full overflow-hidden shadow">
  </div>

  <div class="h-8 w-8 mb-4 lg:mb-0 mr-4">
    <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_3_1.png" alt="" class="h-full w-full rounded-full overflow-hidden shadow">
  </div>

  <div class="h-10 w-10 mb-4 lg:mb-0 mr-4">
    <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_3_2.png" alt="" class="h-full w-full rounded-full overflow-hidden shadow">
  </div>

  <div class="h-12 w-12 mb-4 lg:mb-0 mr-4">
    <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_3_3.png" alt="" class="h-full w-full rounded-full overflow-hidden shadow">
  </div>

  <div class="h-16 w-16 mb-4 lg:mb-0 mr-4">
    <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_3_4.png" alt="" class="h-full w-full rounded-full overflow-hidden shadow">
  </div>

  <div class="h-20 w-20 mb-4 lg:mb-0 mr-4">
    <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_3_5.png" alt="" class="h-full w-full rounded-full overflow-hidden shadow">
  </div>

  <div class="h-24 w-24 mb-4 lg:mb-0 mr-4">
    <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_3_6.png" alt="" class="h-full w-full rounded-full overflow-hidden shadow">
  </div>

  <div class="h-32 w-32 mb-4 lg:mb-0 mr-4">
    <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_3_7.png" alt="" class="h-full w-full rounded-full overflow-hidden shadow">
  </div>

  <div class="w-12 h-12 bg-cover bg-center rounded-md">
    <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_4_0.png" alt="" class="h-full w-full overflow-hidden object-cover rounded-full border-2 border-white dark:border-gray-700 shadow">
  </div>

  <div class="w-12 h-12 bg-cover rounded-md -ml-2">
    <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_4_1.png" alt="" class="h-full w-full overflow-hidden object-cover rounded-full border-2 border-white dark:border-gray-700 shadow">
  </div>

  <div class="w-12 h-12 bg-cover rounded-md bg-center -ml-2">
    <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_4_2.png" alt="" class="h-full w-full overflow-hidden object-cover rounded-full border-2 border-white dark:border-gray-700 shadow">
  </div>

  <div class="w-12 h-12 bg-cover rounded-md -ml-2">
    <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_4_3.png" alt="" class="h-full w-full overflow-hidden object-cover object-center rounded-full border-2 border-white dark:border-gray-700 shadow">
  </div>

  <div class="w-12 h-12 bg-cover rounded-md -ml-2">
    <img src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_4_4.png" alt="" class="h-full w-full overflow-hidden object-cover object-center rounded-full border-2 border-white dark:border-gray-700 shadow">
  </div>
</template>
